### ISSUE TITLE
develop

### ISSUE THREAD

**Issue by Asifdotexe** [Asifdotexe/AniMate#3]
# 📃To-do list

1. **Data Collection and Preprocessing**
   - [x] Collect the data from sites like [MyAnimeList](https://myanimelist.net/)
   - [x] Clean raw data for anime recommendations
   - [x] Store cleaned data in `data/processed`

2. **Build Recommendation System**
   - [x] Define data processing pipeline
   - [x] Implement NLP algorithms for recommendation
   - [x] Create a basic model for recommendations

3. **Code Structure and Implementation**
   - [ ] Develop core functionality in `code/src`
   - [ ] Write scripts for data processing and model training in `code/scripts`
   - [ ] Create and document Jupyter notebooks in `code/notebooks`

4. **Testing**
   - [ ] Implement unit tests
   - [ ] Test data processing and recommendation algorithms
   - [ ] Perform A/B testing

5. **Streamlit Interface**
   - [x] Create a user interface with Streamlit
   - [x] Integrate recommendation system with Streamlit app
   - [x] Test and refine the user interface

## Documentation

1. **Write README File**
   - [ ] Add project description, installation instructions, and usage guide
   - [ ] Include contributing guidelines and branch naming conventions

2. **Create Documentation for Code**
   - [ ] Document functions and modules
   - [ ] Update code comments and docstrings

## Contribution Guidelines

1. **Set Up Contribution Workflow**
   - [ ] Create and document contribution guidelines
   - [ ] Define branch naming conventions (GitFlow strategy)
   - [ ] Specify commit message format (`#<issue-number> "commit message"`)
   - [ ] Describe pull request creation process

2. **Create Issues and Branches**
   - [ ] Create issues for bugs and feature requests
   - [ ] Create feature/bugfix branches according to GitFlow

## Maintenance

1. **Ongoing Development**
   - [ ] Continuously improve the recommendation system
   - [ ] Implement user feedback and new features

2. **Bug Fixes and Updates**
   - [ ] Regularly check for and fix bugs
   - [ ] Update dependencies and libraries

---

**Note:** Regularly update the to-do list as tasks are completed and new tasks are identified.

Contributers
@aditimane07 
@Asifdotexe 
@PranjalDhamane 
@str04 
@tanvisivaraj

**Comment by PranjalDhamane** [comment]
@Asifdotexe  

I see the data has been scraped, the data types appear to be correct because of the helper functions you added during scraping process. Although what I believe the function does is try to cast the datatype  based on the input and return NAN values If there is issue with it and hence it has introduced a lot of NAN values. Could you run the script again without the helper functions to see if that reduces the NAN values provided the data will get dirtier but we can deal with it during the pre-processing stage. 

@tanvisivaraj @str04 @aditimane07 what do you think about this?
